# Numpy Exercises 

In this activity, we will perform some common operation in numpy. 

In [1]:
import numpy as np

## Warm up

Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

In [28]:
a=np.zeros(10)
print("An array of 10 zeros:")
print(a)
print()
b=np.ones(10)
print("An array of 10 ones:")
print(b)
print()

c=np.ones(10)*5
print("An array of 10 fives:")
print(c)


An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## Task 1: 

Write a NumPy program to create a 3X4 matrix and iterate over it and print each element.

In [15]:
# write your program here
a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a, end="\n\n")

print("Each element of the array is:")
for x in np.nditer(a):
  print(x)


Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

Each element of the array is:
10
11
12
13
14
15
16
17
18
19
20
21


In [16]:
# write your program here
a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a, end="\n\n")

print("Each element of the array is:")
for x in a.reshape(-1):
  print(x)


Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

Each element of the array is:
10
11
12
13
14
15
16
17
18
19
20
21


## Task 2: 

Write a NumPy program to compute the multiplication of two given matrixes

In [25]:
# create your function here
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]

result1 = np.dot(p, q)
print(result1)

[[1 2]
 [3 4]]


## Task 3: 

Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis

In [46]:
x = np.arange(12).reshape((2, 6))
print("\nOriginal array:")
print(x)

min_value = np.min(x,axis=1)
print(min_value)

max_value = np.max(x,axis=1)
print(max_value)

difference = max_value - min_value
print(f"Difference between the maximum and the minimum values of the said array: {difference}")


Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[0 6]
[ 5 11]
Difference between the maximum and the minimum values of the said array: [5 5]
